// Solo textos de la UI - Los datos vienen SIEMPRE de la base de datos

// Textos por idioma
export const TEXTOS = {
  es: {
    login: {
      titulo: 'Coggni Cobranzas - Iniciar Sesión',
      usuario: 'Correo Electrónico',
      password: 'Contraseña',
      ingresar: 'Ingresar',
      error: 'Usuario o contraseña incorrectos',
      errorConexion: 'Error de conexión. Por favor, intenta más tarde.',
      errorServidor: 'No se puede conectar con el servidor'
    },
    dashboard: {
      titulo: 'Sistema de Cobranza Automática',
      cerrarSesion: 'Salir',
      fichaFacturas: 'Ficha Facturas',
      estrategiaEnvio: 'Estrategia de Envío',
      arrastrarArchivo: 'Arrastra tu archivo de contactos aquí o haz clic',
      formatosAceptados: 'Archivos Excel o CSV',
      columnasRequeridas: 'Ver columnas requeridas',
      procesarCobranza: 'Procesar Cobranza',
      incluirProximas: 'Incluir facturas próximas a vencer',
      actualizarContactos: 'Actualizar Base de Contactos',
      opcional: 'Opcional',
      dias: 'días',
      whatsappPrioritario: 'WhatsApp Prioritario',
      ambosCanales: 'Ambos Canales',
      soloWhatsapp: 'Solo WhatsApp',
      soloEmail: 'Solo Email',
      resumenConfig: 'Resumen de tu configuración:',
      archivo: 'Archivo',
      estrategia: 'Estrategia',
      recordatorios: 'Recordatorios',
      contactos: 'Contactos',
      procesando: 'Procesando...',
      completado: '¡Proceso completado!',
      error: 'Error',
      errorCarga: 'Error al cargar los datos. Por favor, recarga la página.',
      whatsappDesc: 'Envía primero por WhatsApp cuando esté disponible. Si el cliente no tiene WhatsApp registrado, se enviará automáticamente por Email.',
      ambosDesc: 'Envía por WhatsApp y Email simultáneamente cuando ambos estén disponibles. Máximo alcance garantizado.',
      soloWhatsappDesc: 'Envía únicamente por WhatsApp. Los clientes sin WhatsApp registrado no recibirán el recordatorio.',
      soloEmailDesc: 'Envía únicamente por correo electrónico. Los clientes sin Email registrado no recibirán el recordatorio.',
      anticipacionIntro: 'Seleccione la cantidad de días de anticipación:',
      comoFunciona: '¿Cómo funciona?',
      ejemplo: 'Ejemplo',
      hoy: 'Hoy es',
      con: 'Con',
      diasAnticipacion: 'días de anticipación, se incluirán facturas que venzan hasta el',
      notasAdicionales: 'Notas adicionales:',
      unDia: 'Un valor de 1 día incluye facturas que vencen mañana.',
      maximoDias: 'El máximo configurable es de 10 días de anticipación.',
      actualizarDesc: 'Solo es necesario actualizar si tienes nuevos números de WhatsApp o Emails. El sistema utilizará automáticamente la base de datos vigente si no subes un archivo nuevo.',
      quitar: 'Quitar',
      validando: 'Revisando tu archivo...',
      enviando: 'Preparando información...',
      completadoEstado: 'Completado',
      archivoValido: '¡Perfecto! Tu archivo está listo',
      registrosEncontrados: 'contactos encontrados',
      erroresEncontrados: 'problemas encontrados',
      advertencias: 'observaciones',
      descargarReporte: 'Descargar reporte detallado',
      soloFacturasVencidas: 'Solo facturas vencidas hasta el día de hoy',
      columnasRequeridasArchivo: 'Columnas requeridas en el archivo:',
      anticipacionVencimientos: 'Anticipación de vencimientos:',
      nota: 'Nota',
      columnasRequeridasActualizar: 'Columnas requeridas para actualizar contactos:',
      cuandoApagado: 'Cuando está apagado: sólo se incluirán facturas vencidas al momento de envío.',
      nombresRequierenRevision: 'Nombres que necesitan ajuste',
      facturasNoProcesadas: 'facturas NO serán procesadas',
      monedasAceptadas: 'Monedas aceptadas',
      corrijaMonedas: 'Estas facturas serán ignoradas automáticamente durante el procesamiento. Corrija     las monedas si desea incluirlas.',
    }
  },
  en: {
    login: {
      titulo: 'Coggni Collections - Sign In',
      usuario: 'Email Address',
      password: 'Password',
      ingresar: 'Sign In',
      error: 'Invalid username or password',
      errorConexion: 'Connection error. Please try again later.',
      errorServidor: 'Cannot connect to server'
    },
    dashboard: {
      titulo: 'Automated Collection System',
      cerrarSesion: 'Log out',
      fichaFacturas: 'Invoice File',
      estrategiaEnvio: 'Sending Strategy',
      arrastrarArchivo: 'Drag your contacts file here or click',
      formatosAceptados: 'Excel or CSV files',
      columnasRequeridas: 'View required columns',
      procesarCobranza: 'Process Collection',
      incluirProximas: 'Include upcoming invoices',
      actualizarContactos: 'Update Contact Database',
      opcional: 'Optional',
      dias: 'days',
      whatsappPrioritario: 'WhatsApp Priority',
      ambosCanales: 'Both Channels',
      soloWhatsapp: 'WhatsApp Only',
      soloEmail: 'Email Only',
      resumenConfig: 'Configuration summary:',
      archivo: 'File',
      estrategia: 'Strategy',
      recordatorios: 'Reminders',
      contactos: 'Contacts',
      procesando: 'Processing...',
      completado: 'Process completed!',
      error: 'Error',
      errorCarga: 'Error loading data. Please reload the page.',
      whatsappDesc: 'Send first via WhatsApp when available. If customer has no registered WhatsApp, will automatically send via Email.',
      ambosDesc: 'Send via WhatsApp and Email simultaneously when both are available. Maximum reach guaranteed.',
      soloWhatsappDesc: 'Send only via WhatsApp. Customers without registered WhatsApp will not receive reminders.',
      soloEmailDesc: 'Send only via email. Customers without registered Email will not receive reminders.',
      anticipacionIntro: 'Select the number of days in advance:',
      comoFunciona: 'How does it work?',
      ejemplo: 'Example',
      hoy: 'Today is',
      con: 'With',
      diasAnticipacion: 'days anticipation, invoices due until',
      notasAdicionales: 'Additional notes:',
      unDia: 'A value of 1 day includes invoices due tomorrow.',
      maximoDias: 'Maximum configurable is 10 days anticipation.',
      actualizarDesc: 'Only necessary to update if you have new WhatsApp numbers or Emails. The system will automatically use the current database if you don\'t upload a new file.',
      quitar: 'Remove',
      validando: 'Reviewing your file...',
      enviando: 'Preparing information...',
      completadoEstado: 'Completed',
      archivoValido: 'Perfect! Your file is ready',
      registrosEncontrados: 'contacts found',
      erroresEncontrados: 'issues found',
      advertencias: 'observations',
      descargarReporte: 'Download detailed report',
      soloFacturasVencidas: 'Only invoices due up to today',
      columnasRequeridasArchivo: 'Required columns in file:',
      anticipacionVencimientos: 'Due date anticipation:',
      nota: 'Note',
      columnasRequeridasActualizar: 'Required columns to update contacts:',
      cuandoApagado: 'When off: only overdue invoices at the time of sending will be included.',
      nombresRequierenRevision: 'Names need adjustment',
    }
  }
};